spring:
  application:
    name: order-service
  config:
    import: "optional:configserver:http://config-server:8080"
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/shopcloud
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

resilience4j.circuitbreaker:
  instances:
    productService:
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 5s
      permittedNumberOfCallsInHalfOpenState: 3
    inventoryService:
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 5s
      permittedNumberOfCallsInHalfOpenState: 3

resilience4j.retry:
  instances:
    productService:
      maxAttempts: 3
      waitDuration: 1s
    inventoryService:
      maxAttempts: 3
      waitDuration: 1s


