apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shopcloud

resources:
  - base/config-server
  - base/hello-service

images:
  - name: cloud-config-server
    newName: $DOCKERHUB_USERNAME/cloud-config-server
    newTag: latest
  - name: cloud-hello-service
    newName: $DOCKERHUB_USERNAME/cloud-hello-service
    newTag: latest

configMapGenerator:
  - name: app-versions
    env: versions.env