apiVersion: v1
kind: Service
metadata:
  name: rating-reviews-service
  labels:
    app: rating-reviews-service
spec:
  selector:
    app: rating-reviews-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
